"""Filter application and management."""

from imap_thingy.filters.actions import Action, Delete, MarkAsAnswered, MarkAsRead, MarkAsUnanswered, MarkAsUnread, MoveTo, Trash
from imap_thingy.filters.basic_filters import MoveIfFromFilter, MoveIfToFilter, ProcessHandledFilter
from imap_thingy.filters.criteria import (
    BccContains,
    BccIs,
    BccMatches,
    CcContains,
    CcIs,
    CcMatches,
    Criterion,
    DuplicateCriterion,
    EfficientCriterion,
    FromContains,
    FromIs,
    FromMatches,
    FromMatchesName,
    IsAnswered,
    IsRead,
    IsStarred,
    IsUnanswered,
    IsUnread,
    IsUnstarred,
    OlderThan,
    SelectAll,
    SubjectContains,
    SubjectIs,
    SubjectMatches,
    ToContains,
    ToIs,
    ToMatches,
)
from imap_thingy.filters.criterion import CriterionFilter
from imap_thingy.filters.duplicate import DuplicateFilter
from imap_thingy.filters.interfaces import Filter, OneAccountFilter
from imap_thingy.filters.utils import apply_filters

__all__ = [
    "Filter",
    "OneAccountFilter",
    "CriterionFilter",
    "DuplicateFilter",
    "MoveIfFromFilter",
    "MoveIfToFilter",
    "ProcessHandledFilter",
    "apply_filters",
    "Criterion",
    "EfficientCriterion",
    "SelectAll",
    "FromContains",
    "FromIs",
    "FromMatches",
    "FromMatchesName",
    "IsAnswered",
    "IsRead",
    "IsStarred",
    "IsUnanswered",
    "IsUnread",
    "IsUnstarred",
    "ToContains",
    "ToIs",
    "ToMatches",
    "CcContains",
    "CcIs",
    "CcMatches",
    "BccContains",
    "BccIs",
    "BccMatches",
    "SubjectContains",
    "SubjectIs",
    "SubjectMatches",
    "OlderThan",
    "DuplicateCriterion",
    "Action",
    "MoveTo",
    "Trash",
    "Delete",
    "MarkAsAnswered",
    "MarkAsRead",
    "MarkAsUnanswered",
    "MarkAsUnread",
]
